#!/bin/sh
# vim:ft=sh:noet:ts=3:sw=3:
# file:$GNUPGHOME/exec/pinentry
#==============================================================================#


main() {
	local backend="tty"
	if [ "$PINENTRY_USER_DATA" != nogui ] ; then
		if [ -n "$WAYLAND_DISPLAY" ] || [ -n "$DISPLAY" ] ; then
			backend="gnome3"
		fi
	fi
	exec "/usr/bin/pinentry-$backend" "$@"
} ; main "$@"


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
