#!/hint/bash
# vim:ft=bash:noet:ts=3:sw=3:
# man:systemd-run(1)
# file:$SDRUNIFY_HOME/default.conf
#==============================================================================#


exec {SYSTEMD_ARGS_FD}<< EOF
-pManagedOOMSwap=kill
-pManagedOOMMemoryPressure=kill
EOF


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
