#!/hint/bash
# vim:ft=bash:noet:ts=3:sw=3:
# man:systemd-run(1)
# file:$SDRUNIFY_HOME/pcsx2-qt.conf
#==============================================================================#


if (( "$( < /sys/class/power_supply/ACAD/online )" )) ; then
	unset -v DRI_PRIME
else
	DRI_PRIME="integrated"
fi

if [[ "$DRI_PRIME" == integrated ]] ; then
	DRI_PRIME="pci-0000_c5_00_0"
	MESA_VK_DEVICE_SELECT="1002:15bf!"
else
	DRI_PRIME="pci-0000_03_00_0"
	MESA_VK_DEVICE_SELECT="1002:7480!"
fi ; export DRI_PRIME MESA_VK_DEVICE_SELECT

exec {SYSTEMD_ARGS_FD}<< EOF
--nice=-5
-pManagedOOMSwap=kill
-pManagedOOMMemoryPressure=kill
-ELANG=en_US.UTF-8
-E_JAVA_AWT_WM_NONREPARENTING=1
-EWINIT_X11_SCALE_FACTOR=1
-EDRI_PRIME=$DRI_PRIME
-EMESA_VK_DEVICE_SELECT=$MESA_VK_DEVICE_SELECT
-pUnsetEnvironment=XDG_CURRENT_DESKTOP XDG_SEAT XDG_SESSION_ID XDG_SESSION_CLASS XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_STATE_HOME XDG_CONFIG_DIRS XDG_DATA_DIRS XDG_BIN_DIR XDG_LIB_DIR XDG_DOCUMENTS_DIR XDG_DOWNLOAD_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_TEMPLATES_DIR XDG_VIDEOS_DIR CLUTTER_BACKEND GDK_BACKEND QT_QPA_PLATFORM SDL_VIDEODRIVER WINIT_UNIX_BACKEND XDG_SESSION_TYPE DESKTOP_SESSION XDG_MENU_PREFIX XKB_DEFAULT_LAYOUT XKB_DEFAULT_OPTIONS XCURSOR_SIZE XCURSOR_THEME GTK_THEME QT_QPA_PLATFORMTHEME QT_WAYLAND_DECORATION QT_STYLE_OVERRIDE GDK_DPI_SCALE GDK_SCALE QT_AUTO_SCREEN_SCALE_FACTOR QT_ENABLE_HIGHDPI_SCALING QT_FONT_DPI QT_SCALE_FACTOR SSH_ASKPASS SUDO_ASKPASS
EOF


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
