#!/hint/bash
# ${XDG_CONFIG_HOME}/neofetch/config.conf
# vim:ft=bash:fenc=utf-8:noet:ts=3:sw=3:

: ${HOME:?}

print_info() {
	info title
	info underline

	info 'DIST  ' distro
	info 'KERN  ' kernel
	info 'HOST  ' model
	info underline

	info 'CPU   ' cpu
	info 'RAM   ' memory
	info 'GPU   ' gpu
	info 'RES   ' resolution
	info underline

	info 'UP    ' uptime
	info 'PKG   ' packages
	info 'DISK  ' disk

	info cols
}

ascii_bold=on
ascii_colors=(distro)
ascii_distro=auto
background_color=''
bar_border=on
bar_char_elapsed=■
bar_char_total=■
bar_color_elapsed=distro
bar_color_total=distro
bar_length=10
battery_display=off
block_height=1
block_range=(0 15)
block_width=2
bold=on
col_offset=auto
color_blocks=on
colors=(distro)
cpu_brand=on
cpu_cores=logical
cpu_display=off
cpu_speed=on
cpu_temp=off
crop_mode=normal
crop_offset=center
de_version=off
disk_display=off
disk_percent=off
disk_show=(/)
disk_subtitle=none
distro_shorthand=off
gap=3
gpu_brand=on
gpu_type=all
gtk2=on
gtk3=on
gtk_shorthand=off
image_backend=ascii
image_loop=off
image_size=auto
image_source=ascii
kernel_shorthand=off
memory_display=off
memory_percent=off
memory_unit=mib
mpc_args=()
music_player=mpd
os_arch=on
package_managers=on
public_ip_host='https://ipinfo.io/ip'
public_ip_timeout=3
refresh_rate=on
separator=' '
shell_path=off
shell_version=off
song_format="${MPD_FORMAT:-%artist%:%title%}"
song_shorthand=off
speed_shorthand=off
speed_type=bios_limit
stdout=off
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
title_fqdn=off
underline_char=' '
underline_enabled=on
uptime_shorthand=off
xoffset=0
yoffset=0
