bt-detach-seed-only=true
bt-external-ip=#REDACTED
bt-load-saved-metadata=true
bt-prioritize-piece=head,tail
bt-save-metadata=true
bt-tracker=udp://tracker.opentrackr.org:1337/announce,udp://tracker.openbittorrent.com:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.dler.org:6969/announce
check-integrity=true
dht-listen-port=6881
enable-dht6=true
enable-mmap=true
file-allocation=falloc
force-save=true
listen-port=6881
seed-ratio=5.0
