# ${XDG_CONFIG_HOME}/systemd/user/waybar.service.d/override.conf
# vim:ft=dosini:fenc=utf-8:

[Service]
LockPersonality=true
NoNewPrivileges=true
ProtectProc=invisible
ProtectSystem=full
RestrictSUIDSGID=true

MemoryHigh=100M
MemoryMax=150M
TasksMax=100
