# vim:ft=confini:
# man:foot.ini(5)
# file:$XDG_DATA_HOME/mc/skins/default.ini
#==============================================================================#


[Lines]
horiz=─
vert=│
lefttop=┌
righttop=┐
leftbottom=└
rightbottom=┘
topmiddle=┬
bottommiddle=┴
leftmiddle=├
rightmiddle=┤
cross=┼
dhoriz=─
dvert=│
dlefttop=┌
drighttop=┐
dleftbottom=└
drightbottom=┘
dtopmiddle=┬
dbottommiddle=┴
dleftmiddle=├
drightmiddle=┤

[core]
_default_=lightgray;black
selected=black;white
marked=brown;black
markselect=brown;blue
gauge=black;white
input=lightgray;black
inputunchanged=gray;black
inputmark=black;white
disabled=gray;black
reverse=brown;black
commandlinemark=black;white
header=lightgray;black
inputhistory=
commandhistory=
shadow=gray;black

[dialog]
_default_=lightgray;black
dfocus=black;white
dhotnormal=brightmagenta;black
dhotfocus=white;brightmagenta
dtitle=brightmagenta;black

[error]
_default_=red;black
errdfocus=black;red
errdhotnormal=brightred;black
errdhotfocus=brown;red
errdtitle=brown;black

[filehighlight]
directory=blue;
executable=brightgreen;
symlink=gray;
hardlink =
stalelink=brightred;
device=brightmagenta;
special=gray;
core=red;
temp=gray;
archive=magenta;
doc=lightgray;
source=brightcyan;
media=green;
graph=cyan;
database=brightred;

[menu]
_default_=lightgray;black
menusel=lightgray;blue
menuhot=brown;black
menuhotsel=brown;blue
menuinactive=gray;black

[popupmenu]
_default_=lightgray;black
menusel=lightgray;blue
menutitle=lightgray;black

[buttonbar]
hotkey=brightmagenta;black
button=magenta;black

[statusbar]
_default_=lightgray;black

[help]
_default_=lightgray;black
helpitalic=red;black
helpbold=brown;black
helplink=blue;black
helpslink=lightgray;blue
helptitle=brown;black

[editor]
_default_=lightgray;black
editbold=brown;blue
editmarked=black;cyan
editwhitespace=brightblue;blue
editnonprintable=;black
editlinestate=white;cyan
bookmark=white;red
bookmarkfound=black;green
editrightmargin=brightblue;black
#	editbg=
editframe=gray;
editframeactive=lightgray;
editframedrag=brightblue;

[viewer]
_default_=lightgray;black
viewbold=brown;blue
viewunderline=brightred;blue
viewselected=brown;cyan

[diffviewer]
added=white;brown
changedline=blue;cyan
changednew=red;cyan
changed=white;cyan
removed=white;red
error=red;white


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
