# man:mpv(1)
# file:$XDG_CONFIG_HOME/mpv/mpv.conf
#==============================================================================#


user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36"

#x11-name=mpv
#wayland-app-id=mpv

cache=yes

demuxer-max-bytes=4096M
demuxer-max-back-bytes=512M

cache-pause=no

sub-auto=fuzzy
sub-ass-override=strip
embeddedfonts=no

screenshot-directory=~/Pictures/Screenshots
screenshot-template="%F - [%P] (%#01n)"

watch-later-directory=~/.local/state/mpv/later
watch-later-options-remove=fullscreen,mute,volume

stop-screensaver=no


#==============================================================================#
#                                VIDEO SETTINGS                                #
#==============================================================================#


keep-open=yes

force-window=immediate

profile=fast

hwdec=auto-safe


#==============================================================================#
#                                AUDIO SETTINGS                                #
#==============================================================================#


audio-device=pipewire

audio-channels=auto


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
