# vim:ft=toml:
# file:$XDG_CONFIG_HOME/spotifyd/spotifyd.conf
#==============================================================================#


[global]
device_name = "einherjar"
device_type = "computer"
cache_path = "/home/gaku/.cache/spotifyd"
# no_audio_cache = false
max_cache_size = 4294967296
use_mpris = true
dbus_type = "session"
disable_discovery = true
# zeroconf_port = 1234
backend = "pulseaudio"
device = "default"
audio_format = "S16"
volume_controller = "softvol"
mixer = "PCM"
bitrate = 320
initial_volume = 100
volume_normalisation = true
normalisation_pregain = -10
autoplay = true


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
