# file:$GNUPGHOME/gpg-agent.conf
#==============================================================================#


disable-scdaemon
no-allow-external-cache

pinentry-timeout 60
pinentry-program ~/.gnupg/exec/pinentry

default-cache-ttl 2400
max-cache-ttl     4800

ssh-fingerprint-digest SHA256

enable-ssh-support

default-cache-ttl-ssh 2400
max-cache-ttl-ssh     4800


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
