# file:$GNUPGHOME/gpg-agent.conf
#==============================================================================#


disable-scdaemon
no-allow-external-cache

pinentry-timeout 30

default-cache-ttl 900
max-cache-ttl     3600

ssh-fingerprint-digest SHA256

enable-ssh-support

default-cache-ttl-ssh 900
max-cache-ttl-ssh     3600


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
