# ${GNUPGHOME}/gpg.conf

no-greeting

default-key B6F1C3E092DA04BB7371D4F202471E1B7E9034B2
default-recipient-self

fingerprint
keyid-format 0xlong

personal-cipher-preferences AES256 AES192 AES CAST5
personal-digest-preferences SHA512 SHA384 SHA256 SHA224
