# vim:ft=gpg:
# file:$GNUPGHOME/gpg.conf
#==============================================================================#


no-greeting

auto-key-locate clear,nodefault,local,wkd

default-key B6F1C3E092DA04BB7371D4F202471E1B7E9034B2
default-recipient-self

fingerprint
keyid-format 0xlong
with-keygrip

personal-cipher-preferences TWOFISH AES256 AES192 AES CAST5
personal-compress-preferences BZIP2 ZLIB ZIP Uncompressed
personal-digest-preferences SHA512 SHA384 SHA256 SHA224


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
