bt-external-ip=#REDACTED
bt-tracker=udp://tracker.opentrackr.org:1337/announce,udp://tracker.openbittorrent.com:6969/announce
dht-listen-port=6881
dir=/home/gaku/Downloads
enable-dht6=true
enable-mmap=true
file-allocation=falloc
listen-port=6881
log-level=warn
seed-ratio=5.0
