# vim:ft=confini:
# file:$XDG_CONFIG_HOME/gtk-4.0/settings.ini
#==============================================================================#


[Settings]
gtk-application-prefer-dark-theme=true
gtk-cursor-theme-name=Bibata-Modern-Classic
gtk-cursor-theme-size=16
gtk-decoration-layout=
gtk-enable-animations=false
gtk-enable-event-sounds=false
gtk-enable-input-feedback-sounds=false
gtk-font-name=sans-serif 10
gtk-icon-theme-name=Gruvbox-Dark
gtk-primary-button-warps-slider=true
gtk-shell-shows-desktop=false
gtk-sound-theme-name=freedesktop
gtk-theme-name=Gruvbox-Dark
gtk-xft-antialias=1
gtk-xft-dpi=98304
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
