[ca/desrt/dconf-editor]
show-warning=false

[com/uploadedlobster/peek]
interface-show-notification=false
keybinding-toggle-recording='Pause'
persist-save-folder='/home/gaku/Videos/Screencasts'

[io/github/seadve/Kooha]
saving-location=b'/home/gaku/Videos/Screencasts'

[org/gnome/desktop/interface]
color-scheme='prefer-dark'
cursor-size=16
cursor-theme='Bibata-Modern-Classic'
document-font-name='sans-serif 10'
enable-animations=false
font-antialiasing='rgba'
font-hinting='full'
font-name='sans-serif 10'
font-rgba-order='rgb'
gtk-theme='Gruvbox-Dark'
icon-theme='Gruvbox-Dark'
monospace-font-name='monospace 10'
scaling-factor=1
text-scaling-factor=1.0
toolbar-icons-size='small'
toolbar-style='text'

[org/gnome/desktop/privacy]
disable-camera=true
disable-microphone=true

[org/gnome/desktop/sound]
event-sounds=false
input-feedback-sounds=false
theme-name='freedesktop'

[org/gnome/desktop/wm/preferences]
audible-bell=false
theme='Gruvbox-Dark'
titlebar-font='sans-serif 10'

[org/gnome/gnome-system-monitor]
disks-interval=100000
graph-update-interval=2000
network-in-bits=true
network-total-in-bits=true
show-all-fs=true
show-dependencies=true
show-whose-processes='all'
smooth-refresh=true
solaris-mode=true
update-interval=2000

[org/gnome/gnome-system-monitor/disksview]
col-available-visible=false
col-device-visible=true
col-directory-visible=true
col-free-visible=false
col-total-visible=true
col-type-visible=true
col-used-visible=true
columns-order=['type', 'device', 'directory', 'available', 'used', 'total', 'free']

[org/gnome/gnome-system-monitor/proctree]
col-0-visible=true
col-10-visible=false
col-11-visible=false
col-12-visible=true
col-14-visible=true
col-15-visible=true
col-17-visible=false
col-18-visible=false
col-2-visible=true
col-24-visible=true
col-25-visible=true
col-26-visible=true
col-3-visible=false
col-4-visible=false
col-6-visible=false
col-7-visible=false
col-8-visible=true
col-9-visible=false
columns-order=[12, 26, 0, 1, 2, 8, 15, 24, 25, 17, 3, 4, 6, 7, 9, 10, 11, 13, 14, 16, 18, 19, 20, 21, 22, 23]

[org/gnome/software]
download-updates=false
download-updates-notify=false
show-only-verified-apps=true
