#!/hint/sh
# ${XDG_CONFIG_HOME}/environment.d/bemenu.conf
# vim:ft=sh:fenc=utf-8:

BEMENU_OPTS='--bottom --ignorecase --line-height=27 --monitor=1 --prompt=: --wrap --fn "sans-serif 13" --fb #151515cc --ff #90a959ff --hb #151515cc --hf #90a959ff --nb #151515cc --nf #f5f5f5ff --sb #151515cc --sf #90a959ff --tb #151515cc --tf #f5f5f5ff --scb #151515cc --scf #151515cc'
