#!/hint/sh
# ${XDG_CONFIG_HOME}/environment.d/compose.conf
# vim:ft=sh:fenc=utf-8:

: ${XDG_CACHE_HOME:?} ${XDG_CONFIG_HOME:?}

XCOMPOSECACHE="${XDG_CACHE_HOME}/compose"
XCOMPOSEFILE="${XDG_CONFIG_HOME}/X11/compose"
