#!/hint/sh
# ${XDG_CONFIG_HOME}/environment.d/defaults.conf
# vim:ft=sh:fenc=utf-8:

BROWSER=chromium
DIFFPROG='diff --minimal --new-file --unified'
EDITOR=vim
FCEDIT=vim
PAGER=less
TERMINAL=alacritty
VISUAL=vim
