#!/hint/sh
# ${XDG_CONFIG_HOME}/environment.d/less.conf
# vim:ft=sh:fenc=utf-8:

: ${XDG_CONFIG_HOME:?}

LESS='--RAW-CONTROL-CHARS --chop-long-lines --ignore-case --incsearch --line-numbers --mouse --no-histdups --quit-if-one-screen --tabs 3 --tilde'
LESSCHARSET=utf-8
LESSCLOSE="${XDG_CONFIG_HOME}/less/exec/close.sh '%s' '%s'"
LESSHISTFILE="${XDG_CONFIG_HOME}/less/history"
LESSHISTSIZE=10000
#LESSKEY="${XDG_CONFIG_HOME}/less/keys"
LESSOPEN="${XDG_CONFIG_HOME}/less/exec/open.sh '%s'"
