#!/hint/sh
# ${XDG_CONFIG_HOME}/environment.d/paths.conf
# vim:ft=sh:fenc=utf-8:

: ${PATH:?} ${XDG_BIN_DIR:?} ${XDG_LIB_DIR:?}

LD_LIBRARY_PATH="${XDG_LIB_DIR}/.overrides:/usr/local/lib:/usr/lib:${XDG_LIB_DIR}"
PATH="${XDG_BIN_DIR}/.overrides:${PATH}:${XDG_BIN_DIR}"
