#!/hint/sh
# ${XDG_CONFIG_HOME}/environment.d/python.conf
# vim:ft=sh:fenc=utf-8:

: ${XDG_CONFIG_HOME:?}

PYTHONHISTORY="${XDG_CONFIG_HOME}/python/history"
PYTHONHISTORYSIZE=10000
PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/init"
