#!/hint/sh
# vim:ft=sh:
# man:environment.d(5)
# file:$XDG_CONFIG_HOME/environment.d/ssh-agent.conf
#==============================================================================#


# man:ssh(1)
SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh"


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
