#!/hint/sh
# ${XDG_CONFIG_HOME}/environment.d/wine.conf
# vim:ft=sh:fenc=utf-8:

: ${XDG_BIN_DIR:?} ${XDG_DATA_HOME:?}

WINELOADER="${XDG_BIN_DIR}/.overrides/wine"
WINEPREFIX="${XDG_DATA_HOME}/wine/prefix"
