# vim:ft=yaml:et:ts=2:sw=2:
# man:udiskie(8)
# file:$XDG_CONFIG_HOME/lazygit/config.yml
#==============================================================================#


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
