#!/bin/sh
# ${XDG_CONFIG_HOME}/Wayland/clean.d/50-systemd-user.sh
# vim:ft=sh:fenc=utf-8:noet:ts=3:sw=3:

systemctl --user unset-environment CLUTTER_BACKEND DESKTOP_SESSION GDK_BACKEND QT_QPA_PLATFORM SDL_VIDEODRIVER XDG_SESSION_TYPE WINIT_UNIX_BACKEND DISPLAY WAYLAND_DISPLAY SWAYSOCK
dbus-update-activation-environment CLUTTER_BACKEND DESKTOP_SESSION GDK_BACKEND QT_QPA_PLATFORM SDL_VIDEODRIVER XDG_SESSION_TYPE WINIT_UNIX_BACKEND DISPLAY WAYLAND_DISPLAY SWAYSOCK
