#!/bin/sh
# ${XDG_CONFIG_HOME}/Wayland/compositor
# vim:ft=sh:fenc=utf-8:noet:ts=3:sw=3:

set -a
eval "$(printf '%s=wayland;' CLUTTER_BACKEND DESKTOP_SESSION GDK_BACKEND QT_QPA_PLATFORM SDL_VIDEODRIVER XDG_SESSION_TYPE WINIT_UNIX_BACKEND)"
set +a

(sleep 2; systemctl --user start Wayland.target) & exec sway
