#!/hint/bash
# ${XDG_CONFIG_HOME}/pacman/makepkg.conf
# vim:ft=bash:fenc=utf-8:

: ${HOME:?} ${USER:?}

LOGDEST="${XDG_DATA_HOME:-${HOME}/.local/share}/pacman/logs"
PACKAGER='GaKu999 <g4ku999@gmail.com>'
PKGDEST="/srv/pacman/pkg/${SUDO_USER:-${USER}}"
SRCPKGDEST="/srv/pacman/src/${SUDO_USER:-${USER}}"

MAKEFLAGS="-j$(nproc)"

RUSTFLAGS='-C opt-level=2'
DEBUG_RUSTFLAGS='-C debuginfo=2'

BUILDDIR="/tmp/makepkg-${SUDO_USER:-${USER}}"
BUILDENV=(!distcc color !ccache check sign)

INTEGRITY_CHECK=(sha256)
