#!/hint/sh
# ${XDG_CONFIG_HOME}/sh/logout
# vim:ft=sh:fenc=utf-8:noet:ts=3:sw=3:

read -p 'Linger? [y/N]: ' reply
case "${reply}" in
[Yy]*) loginctl enable-linger ;;
*) loginctl disable-linger ;;
esac

stty sane
