#!/hint/bash
# ${XDG_CONFIG_HOME}/bash/init
# vim:ft=bash:fenc=utf-8:noet:ts=3:sw=3:

: ${HOME:?}

. "${ENV:-${XDG_CONFIG_HOME:-${HOME}/.config}/sh/init}"

[[ "${-}" == *i* ]] || return 0

: ${HOSTNAME:?} ${PWD:?} ${USER:?}

. "${XDG_CONFIG_HOME:-${HOME}/.config}/bash/alias"
. "${XDG_CONFIG_HOME:-${HOME}/.config}/bash/functions"

set -o notify
shopt -s autocd cdable_vars cdspell checkhash complete_fullquote direxpand dirspell dotglob extglob globstar histappend histreedit histverify progcomp_alias

. /usr/share/doc/pkgfile/command-not-found.bash
. /usr/share/git/completion/git-prompt.sh

GIT_PS1_COMPRESSSPARSESTATE=1
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHStATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM=auto
GIT_PS1_STATESEPARATOR=:

HISTCONTROL=ignoreboth:erasedups
HISTFILE="${XDG_CONFIG_HOME:-${HOME}/.config}/bash/history"
HISTTIMEFORMAT='[%x %X] '

__wdmask() {
	local mask=()

	[[ "${PWD}" == "$(realpath --quiet -- "${PWD}")" ]] || mask+=(l)
	[[ -w "${PWD}" ]] || mask+=(w)
	[[ ! -u "${PWD}" ]] || mask+=(s)
	[[ ! -g "${PWD}" ]] || mask+=(S)
	[[ ! -k "${PWD}" ]] || mask+=(t)

	! (("${#mask[@]}")) || printf '!%s' "${mask[@]}"
}

PROMPT_COMMAND=('echo' 'printf "\033[1mTIME:\033[0m \033[1;36m%s\033[0m\n" "$(date "+%H:%M")"' 'printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#${HOME}/\~}"')
PS1='\033[1;33m\u\033[0m@\033[1;31m\h\033[0m:\033[1;34m\w\033[0m\033[1;31m$(__wdmask)\033[0m$(__git_ps1 ":\033[1;36m%s\033[0m")\n\$ '
PS3='? '

__error_code() {
	printf '\033[1mCODE:\033[0m \033[1;31m%s\033[0m\n' "${?}"
}
trap __error_code ERR

neofetch

if [ -n "$(todos)" ]; then
	echo Todos:
	todos
	echo
fi

if [ -n "$(when --noheader)" ]; then
	echo Calendar:
	when --noheader
	echo
fi

echo Fortune:
fortune -a
