# ${XDG_CONFIG_HOME}/mpd/mpd.conf
# vim:ft=conf:fenc=utf-8:noet:ts=3:sw=3:

db_file      "~/.config/mpd/database.sql"
sticker_file "~/.config/mpd/sticker.sql"

music_directory    "~/Music"
playlist_directory "~/Music/.playlists"

auto_update                      "yes"
follow_inside_symlinks           "yes"
follow_outside_symlinks          "yes"
restore_paused                   "yes"
save_absolute_paths_in_playlists "yes"

filesystem_charset "UTF-8"

metadata_to_use "artist,album,title,track,name,genre,date,composer,performer,disc"

bind_to_address "~/.local/run/mpd/socket"
pid_file        "~/.local/run/mpd/pid"
port            "6600"
state_file      "~/.local/run/mpd/state"

audio_output {
	type "pulse"
	name "PulseAudio"
}

audio_output {
	type   "fifo"
	name   "FIFO"
	path   "~/.local/run/mpd/fifo"
	format "44100:16:2"
}
