--disk-cache-size=1
--enable-accelerated-video-decode
--enable-features=UseOzonePlatform
--enable-features=WebUIDarkMode
--enable-gpu-rasterization
--enable-reader-mode
--enable-system-notifications
--enable-zero-copy
--force-dark-mode
--media-cache-size=1
--process-per-site
