# vim:ft=dircolors:
# man:dircolors(1)
# file:$XDG_CONFIG_HOME/dircolors.conf
#==============================================================================#


RESET 0
DIR 94
LINK target
FIFO 33
SOCK 35
DOOR 35
BLK 33
CHR 33
ORPHAN 31
SETUID 97;41
SETGID 97;43
STICKY_OTHER_WRITABLE 97;42
OTHER_WRITABLE 94;42
STICKY 97;44
EXEC 92


#==============================================================================#
#                          EXECUTABLE & SCRIPT FILES                           #
#==============================================================================#


.bash 92
.bat 92
.btm 92
.cmd 92
.com 92
.csh 92
.exe 92
.job 92
.js 92
.lua 92
.perl 92
.py 92
.sh 92
.zsh 92


#==============================================================================#
#                          ARCHIVE & COMPRESSED FILES                          #
#==============================================================================#


.7z 91
.Z 91
.ace 91
.alz 91
.apk 91
.arc 91
.arj 91
.bz 91
.bz2 91
.cab 91
.cpio 91
.crate 91
.deb 91
.drpm 91
.dwm 91
.dz 91
.ear 91
.egg 91
.esd 91
.gpg 91
.gz 91
.iso 91
.jar 91
.lha 91
.lrz 91
.lz 91
.lz4 91
.lzh 91
.lzma 91
.lzo 91
.pyz 91
.rar 91
.rpm 91
.rz 91
.sar 91
.sfs 91
.swm 91
.t7z 91
.tZ 91
.tar 91
.taz 91
.tbz 91
.tbz2 91
.tgz 91
.tlz 91
.txz 91
.tz 91
.tzo 91
.tzst 91
.udeb 91
.war 91
.whl 91
.wim 91
.xz 91
.z 91
.zip 91
.zoo 91
.zst 91


#==============================================================================#
#                                DOCUMENT FILES                                #
#==============================================================================#


.docx 91
.odt 91
.pdf 91
.xcf 91


#==============================================================================#
#                                 IMAGE FILES                                  #
#==============================================================================#


.asf 93
.avi 93
.avif 93
.bmp 93
.cgm 93
.dl 93
.emf 93
.flc 93
.fli 93
.flv 93
.gif 93
.gl 93
.jpeg 93
.jpg 93
.jxl 93
.m2v 93
.m4v 93
.mjpeg 93
.mjpg 93
.mkv 93
.mng 93
.mov 93
.mp4 93
.mp4v 93
.mpeg 93
.mpg 93
.nuv 93
.ogm 93
.pbm 93
.pcx 93
.pgm 93
.png 93
.ppm 93
.qt 93
.rm 93
.rmvb 93
.svg 93
.svgz 93
.tga 93
.tif 93
.tiff 93
.vob 93
.webm 93
.wmv 93
.xbm 93
.xcf 93
.xpm 93
.xwd 93
.yuv 93


#==============================================================================#
#                                 AUDIO FILES                                  #
#==============================================================================#


.aac 96
.au 96
.flac 96
.m4a 96
.mid 96
.midi 96
.mka 96
.mp3 96
.mpc 96
.oga 96
.ogg 96
.opus 96
.ra 96
.spx 96
.wav 96
.xspf 96


#==============================================================================#
#                                 VIDEO FILES                                  #
#==============================================================================#


.avi 95
.mkv 95
.mp4 95
.mpg 95
.ogv 95
.ogx 95


#==============================================================================#
#                                BACKUP FILES                                  #
#==============================================================================#


*~ 90
*# 90
.bak 90
.crdownload 90
.dpkg-dist 90
.dpkg-new 90
.dpkg-old 90
.dpkg-tmp 90
.old 90
.orig 90
.pacsave 90
.part 90
.rej 90
.rpmnew 90
.rpmorig 90
.rpmsave 90
.swp 90
.tmp 90
.ucf-dist 90
.ucf-new 90
.ucf-old 90


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
