# ${XDG_CONFIG_HOME}/mbsync.conf
# vim:ft=conf:fenc=utf-8:

SyncState *

IMAPAccount     gmail-public
Host            imap.gmail.com
user            g4ku999@gmail.com
PassCmd         "pass show google.com/public/isync | head --lines 1"
SSLType         IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore gmail-public-remote
Account   gmail-public

MaildirStore gmail-public-local
Subfolders   Verbatim
Path         ~/.local/mail/GMAIL/PUBLIC/
Inbox        ~/.local/mail/GMAIL/PUBLIC/INBOX

Channel  gmail-public-inbox
Far      :gmail-public-remote:
Near     :gmail-public-local:
Patterns "INBOX"

Channel gmail-public-sent
Far     :gmail-public-remote:"[Gmail]/Sent Mail"
Near    :gmail-public-local:SENT
Create  Near

Channel gmail-public-draft
Far     :gmail-public-remote:"[Gmail]/Drafts"
Near    :gmail-public-local:DRAFT
Create  Near

Channel gmail-public-archive
Far     :gmail-public-remote:"Backup"
Near    :gmail-public-local:ARCHIVE
Create  Near

Channel gmail-public-spam
Far     :gmail-public-remote:"[Gmail]/Spam"
Near    :gmail-public-local:SPAM
Create  Near

Channel gmail-public-trash
Far     :gmail-public-remote:"[Gmail]/Trash"
Near    :gmail-public-local:TRASH
Create  Near

Group   gmail-public-group
Channel gmail-public-inbox
Channel gmail-public-sent
Channel gmail-public-draft
Channel gmail-public-archive
Channel gmail-public-spam
Channel gmail-public-trash

IMAPAccount     gmail-private
Host            imap.gmail.com
user            #REDACTED
PassCmd         "pass show google.com/private/isync | head --lines 1"
SSLType         IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore gmail-private-remote
Account   gmail-private

MaildirStore gmail-private-local
Subfolders   Verbatim
Path         ~/.local/mail/GMAIL/PRIVATE/
Inbox        ~/.local/mail/GMAIL/PRIVATE/INBOX

Channel  gmail-private-inbox
Far      :gmail-private-remote:
Near     :gmail-private-local:
Patterns "INBOX"

Channel gmail-private-sent
Far     :gmail-private-remote:"[Gmail]/Sent Mail"
Near    :gmail-private-local:SENT
Create  Near

Channel gmail-private-draft
Far     :gmail-private-remote:"[Gmail]/Drafts"
Near    :gmail-private-local:DRAFT
Create  Near

Channel gmail-private-archive
Far     :gmail-private-remote:"Backup"
Near    :gmail-private-local:ARCHIVE
Create  Near

Channel gmail-private-spam
Far     :gmail-private-remote:"[Gmail]/Spam"
Near    :gmail-private-local:SPAM
Create  Near

Channel gmail-private-trash
Far     :gmail-private-remote:"[Gmail]/Trash"
Near    :gmail-private-local:TRASH
Create  Near

Group   gmail-private-group
Channel gmail-private-inbox
Channel gmail-private-sent
Channel gmail-private-draft
Channel gmail-private-archive
Channel gmail-private-spam
Channel gmail-private-trash

Group   gmail-group
Channel gmail-public-inbox
Channel gmail-public-sent
Channel gmail-public-draft
Channel gmail-public-archive
Channel gmail-public-spam
Channel gmail-public-trash
Channel gmail-private-inbox
Channel gmail-private-sent
Channel gmail-private-draft
Channel gmail-private-archive
Channel gmail-private-spam
Channel gmail-private-trash

MaildirStore backup
Subfolders   Verbatim
Path         ~/.local/mail/BACKUP/

Channel gmail-public-backup
Far     :gmail-public-remote:"Backup"
Near    :backup:"GMAIL/PUBLIC"
Create  Near
Expunge Near
Sync    Pull

Channel gmail-private-backup
Far     :gmail-private-remote:"Backup"
Near    :backup:"GMAIL/PRIVATE"
Create  Near
Expunge Near
Sync    Pull

Group   gmail-backup-group
Channel gmail-public-backup
Channel gmail-private-backup
