# ${XDG_CONFIG_HOME}/notmuch.conf
# vim:ft=dosini:fenc=utf-8:

[database]
path=/home/gaku/.local/mail

[user]
name=GaKu999
primary_email=g4ku999@gmail.com
other_email=#REDACTED;

[maildir]
synchronize_flags=true

[new]
tags=new;
ignore=.mbsyncstate;.uidvalidity;

[search]
exclude_tags=deleted;spam;
