# man:picom(1)
# file:$XDG_CONFIG_HOME/picom.conf
#==============================================================================#


shadow = false ;
fading = false ;
backend = "glx" ;
vsync = true ;


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
