# ${XDG_CONFIG_HOME}/picom.conf
# vim:ft=conf:fenc=utf-8:

backend                   = "glx";
fading                    = false;
frame-opacity             = 0.8;
inactive-opacity-override = true;
shadow                    = false;
vsync                     = true;
