# ${XDG_CONFIG_HOME}/readline.conf
# vim:ft=readline:fenc=utf-8:

$include /etc/inputrc

set bell-style                 audible
set bind-tty-special-chars     on
set blink-matching-paren       on
set colored-completion-prefix  on
set colored-stats              on
set enable-bracketed-paste     on
set echo-control-characters    off
set mark-symlinked-directories on
set show-mode-in-prompt        on

$if term=linux

set vi-cmd-mode-string "\1\033[?8c\2"
set vi-ins-mode-string "\1\033[?0c\2"

$else

set vi-cmd-mode-string "\1\033[0 q\2"
set vi-ins-mode-string "\1\033[3 q\2"

$endif

set show-all-if-ambiguous  on
set show-all-if-unmodified on
set completion-ignore-case on

set visible-stats on

set editing-mode vi

$if mode=vi

set keymap vi-command
"\0332[~": overwrite-mode
"\0331[~": beginning-of-line
"\0334[~": end-of-line
"\0333[~": delete-char
"\033[A":  history-search-backward
"\033[B":  history-search-forward
j:         history-search-backward
k:         history-search-forward
"\033.":   yank-last-arg
"\033n":   yank-nth-arg
Control-l: clear-screen

set keymap vi-insert
"\0332[~": overwrite-mode
"\0331[~": beginning-of-line
"\0334[~": end-of-line
"\0333[~": delete-char
"\033[A":  history-search-backward
"\033[B":  history-search-forward
"\033.":   yank-last-arg
"\033n":   yank-nth-arg
Control-l: clear-screen

$endif
