# ${XDG_CONFIG_HOME}/gtk-3.0/settings.ini
# vim:ft=dosini:fenc=utf-8:

[Settings]
gtk-application-prefer-dark-theme=1
gtk-button-images=0
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=36
gtk-decoration-layout=""
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-enable-primary-paste=1
gtk-font-name=serif 16
gtk-icon-theme-name=Adwaita
gtk-key-theme-name=Default
gtk-menu-images=0
gtk-sound-theme-name=none
gtk-theme-name=Adwaita
gtk-toolbar-icon-size=GTK_ICON_SIZE_SMALL_TOOLBAR
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-xft-antialias=1
gtk-xft-dpi=96
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
