#!/hint/bash
# ${XDG_CONFIG_HOME}/wrapper/systemd/chromium.conf
# vim:ft=bash:fenc=utf-8:noet:ts=3:sw=3:

: ${DISPLAY:?}

cat <<EOF
--property StandardInput=null
--property StandardOutput=null
--property StandardError=null
--property LockPersonality=true
--property NoNewPrivileges=true
--property ProtectProc=invisible
--property ProtectSystem=full
--property RestrictSUIDSGID=true
--property MemoryHigh=4G
--property MemoryMax=6G
--property TasksMax=1000
--setenv DISPLAY=${DISPLAY}
EOF
