#!/hint/bash
# ${XDG_CONFIG_HOME}/wrapper/systemd/wine.conf
# vim:ft=bash:fenc=utf-8:noet:ts=3:sw=3:

: ${DISPLAY:?}

cat <<EOF
--same-dir
--property StandardInput=null
--property StandardOutput=null
--property StandardError=null
--property LockPersonality=true
--property NoNewPrivileges=true
--property ProtectProc=invisible
--property ProtectSystem=full
--property RestrictSUIDSGID=true
--property MemoryHigh=8G
--property MemoryMax=10G
--property TasksMax=500
--setenv DISPLAY=${DISPLAY}
--setenv CLUTTER_BACKEND=x11
--setenv DESKTOP_SESSION=x11
--setenv GDK_BACKEND=x11
--setenv QT_QPA_PLATFORM=xcb
--setenv SDL_VIDEODRIVER=x11
--setenv XDG_SESSION_TYPE=x11
--setenv WINIT_UNIX_BACKEND=x11
--setenv WINIT_X11_SCALE_FACTOR=1
EOF
