# vim:ft=confini:
# man:alacritty(5)
# man:alacritty-bindings(5)
# file:$XDG_CONFIG_HOME/alacritty/alacritty.toml
#==============================================================================#


[general]
import = ["themes/default.toml"]
live_config_reload = false

[font]
normal.family = "monospace"
size = 10

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[[hints.enabled]]
action = "Copy"
hyperlinks = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
