# vim:ft=confini:
# man:alacritty(5)
# man:alacritty-bindings(5)
# file:$XDG_CONFIG_HOME/alacritty/alacritty.toml
#==============================================================================#


[window]
opacity = 0.95

[font]
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xclip"
hyperlinks = true
post_processing = true
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"


#==============================================================================#
#                                   KEYBINDS                                   #
#==============================================================================#


[keyboard]
bindings = [
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]


#==============================================================================#
#                                    COLORS                                    #
#==============================================================================#


[colors]
draw_bold_text_with_bright_colors = true

line_indicator = { foreground = "#f5f5f5", background = "#505050" }
footer_bar = { foreground = "#d0d0d0", background = "#151515" }
selection = { text = "#f5f5f5", background = "#505050" }

[colors.normal]
black = "#151515"
red = "#732b2c"
green = "#60713b"
yellow = "#a37f4e"
blue = "#476a79"
magenta = "#714e6a"
cyan = "#4e7971"
white = "#d0d0d0"

[colors.bright]
black = "#505050"
red = "#ac4142"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#f5f5f5"

[colors.dim]
black = "#151515"
red = "#732b2c"
green = "#60713b"
yellow = "#a37f4e"
blue = "#476a79"
magenta = "#714e6a"
cyan = "#4e7971"
white = "#d0d0d0"

[colors.primary]
background = "#151515"
foreground = "#d0d0d0"
dim_foreground = "#505050"
bright_foreground = "#f5f5f5"

[colors.search]
matches = { foreground = "#f5f5f5", background = "#505050" }
focused_match = { foreground = "#f5f5f5", background = "#505050" }

[colors.hints]
start = { foreground = "#f4bf75", background = "#505050" }
end = { foreground = "#f4bf75", background = "#505050" }


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
