[*]
wallpaper_mode=crop
wallpaper_common=1
wallpaper=/home/gaku/.wallpaper
desktop_bg=#1d2021
desktop_fg=#ebdbb2
desktop_shadow=#000000
desktop_font=Sans 12
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_trash=0
show_mounts=0
