# vim:ft=confini:
# man:polybar(5)
# file:$XDG_CONFIG_HOME/polybar/config.ini
#==============================================================================#


include-file="themes/default.ini"

[bar/default]
background=${colors.background}
foreground=${colors.foreground}

border-size=2px
border-color=${colors.color0}

font-0=sans-serif:size=15
font-1=Symbols Nerd Font:size=16
font-2=sans-serif:pixelsize=2
font-3=sans-serif:size=15
font-4=sans-serif:size=14

modules-left=logo separator xworkspaces separator xkeyboard separator
modules-center=xwindow
modules-right=separator mails-new mails-cur updates separator cpu memory gpu filesystem separator temperature separator battery separator ether wlan separator pulseaudio separator backlight separator date tray

[settings]
screenchange-reload=true
pseudo-transparency=false

[module/separator]
type=custom/text

label=%{T3}|%{T-}
label-background=${colors.color0}
label-foreground=${colors.color0}
label-margin=2px

[module/logo]
type=custom/text

label=%{A1:xdotool sleep 0.2 key --delay 50 super+Menu:}%{A3:xdgctl -A menu:}%{T2}%{T-}%{A}%{A}
label-foreground=#1793d1
label-margin=2px

[module/mails-new]
type=custom/script

interval=60

exec=mails count new

label=%{A1:xdg-run thunderbird:}%{A3:mails sync --pull posteo-inbox:}%{T2}%{T-}%{T5}%output%%{T-}%{A}%{A}
label-foreground=${colors.color13}
label-margin=2px

[module/mails-cur]
type=custom/script

interval=60

exec=mails count cur

label=%{A1:xdg-run thunderbird:}%{A3:mails sync --push posteo-inbox:}%{T2}%{T-}%{T5}%output%%{T-}%{A}%{A}
label-foreground=${colors.color13}
label-margin=2px

[module/updates]
type=custom/script

interval=60

exec=updates count

label=%{A1:updates notify:}%{A3:updates check:}%{A2:alacritty-msg -e updates update:}%{T2}󰏓%{T-}%{T5}%output%%{T-}%{A}%{A}%{A}
label-foreground=${colors.color13}
label-margin=2px

[module/xworkspaces]
type=internal/xworkspaces

enable-scroll=true

label-active=%{T4}%name%%{T-}
label-active-background=${colors.color0}
label-active-foreground=${colors.foreground}
label-active-margin=2px

label-occupied=%{T4}%name%%{T-}
label-occupied-foreground=${colors.color8}
label-occupied-margin=2px

label-urgent=%{T4}%name%%{T-}
label-urgent-foreground=${colors.color11}
label-urgent-margin=2px

label-empty=
label-empty-margin=0px

[module/xkeyboard]
type=internal/xkeyboard

blacklist-0=num lock
blacklist-1=scroll lock
blacklist-2=caps lock

label-layout=%{T2}󰌌%{T-}%{T5}%layout%%{T-}
label-layout-foreground=${colors.color13}
label-layout-margin=2px

[module/xwindow]
type=internal/xwindow

label=%{T5}%title%%{T-}
label-maxlen=50
label-foreground=${colors.foreground}
label-margin=2px

label-empty=
label-empty-margin=0px

[module/cpu]
type=internal/cpu

interval=10
warn-percentage=75

label=%{A3:xdg-run gnome-system-monitor:}%{T2}%{T-}%{T5}%percentage%%%{T-}%{A}
label-foreground=${colors.color13}
label-margin=2px

label-warn=%{A3:xdg-run gnome-system-monitor:}%{T2}%{T-}%{T5}%percentage%%%{T-}%{A}
label-warn-foreground=${colors.color9}
label-warn-margin=2px

[module/memory]
type=internal/memory

interval=10
warn-percentage=75

label=%{A3:xdg-run gnome-system-monitor:}%{T2}%{T-}%{T5}%percentage_used%%%{T-}%{A}
label-foreground=${colors.color13}
label-margin=2px

label-warn=%{A3:xdg-run gnome-system-monitor:}%{T2}%{T-}%{T5}%percentage_used%%%{T-}%{A}
label-warn-foreground=${colors.color9}
label-warn-margin=2px

[module/gpu]
type=custom/script

interval=10

exec=sh -c 'if grep -q D0 /sys/class/drm/card1/device/power_state ; then if [ -f /sys/class/drm/card1/device/gpu_busy_percent ] ; then cat /sys/class/drm/card1/device/gpu_busy_percent ; else echo -n 0 ; fi ; fi'

label=%{T2}󰢮%{T-}%{T5}%output%%%{T-}
label-foreground=${colors.color13}
label-margin=2px

[module/temperature]
type=internal/temperature

interval=10
thermal-zone=0
base-temperature=40
warn-temperature=100

units=true

format=%{T2}<ramp>%{T-}%{T5}<label>%{T-}
format-foreground=${colors.color11}
format-margin=2px
format-warn=%{T2}<ramp>%{T-}%{T5}<label-warn>%{T-}
format-warn-foreground=${colors.color9}
format-warn-margin=2px

label=%temperature-c%
label-warn=%temperature-c%

ramp-0=
ramp-1=
ramp-2=
ramp-3=
ramp-4=

[module/filesystem]
type=internal/fs

interval=60
warn-percentage=75

mount-0=/home

label-mounted=%{A3:pcmanfm:}%{A2:xdg-run baobab:}%{T2}󰋊%{T-}%{T5}%percentage_used%%%{T-}%{A}%{A}
label-mounted-foreground=${colors.color13}
label-margin=2px

label-warn=%{A3:pcmanfm:}%{A2:xdg-run baobab:}%{T2}󰋊%{T-}%{T5}%percentage_used%%%{T-}%{A}%{A}
label-warn-foreground=${colors.color9}
label-warn-margin=2px

label-unmounted=
label-unmounted-margin=2px

[module/battery]
type=internal/battery

low-at=25
poll-interval=60

format-charging=%{A3:xdg-run gnome-power-statistics:}%{A2:xfce4-power-manager -c:}%{T2}<ramp-capacity>%{T-}%{T5}<label-charging>%{T-}%{A}%{A}
format-charging-foreground=${colors.color10}
format-charging-margin=2px

format-discharging=%{A3:xdg-run gnome-power-statistics:}%{A2:xfce4-power-manager -c:}%{T2}<ramp-capacity>%{T-}%{T5}<label-discharging>%{T-}%{A}%{A}
format-discharging-foreground=${colors.color11}
format-discharging-margin=2px

format-full=%{A3:xdg-run gnome-power-statistics:}%{A2:xfce4-power-manager -c:}%{T2}<ramp-capacity>%{T-}%{T5}<label-full>%{T-}%{A}%{A}
format-full-foreground=${colors.color10}
format-full-margin=2px

format-low=%{A3:xdg-run gnome-power-statistics:}%{A2:xfce4-power-manager -c:}%{T2}<ramp-capacity>%{T-}%{T5}<label-low>%{T-}%{A}%{A}
format-low-foreground=${colors.color9}
format-low-margin=2px

label-charging=%percentage%%
label-discharging=%percentage%%
label-full=%percentage%%
label-low=%percentage%%

ramp-capacity-0=
ramp-capacity-1=
ramp-capacity-2=
ramp-capacity-3=
ramp-capacity-4=

[module/ether]
type=internal/network

interval=60
interface-type=wired

label-connected=%{A3:xdg-run gnome-nettool:}%{T2}%{T-}%{T5}%local_ip%%{T-}%{A}
label-connected-foreground=${colors.color10}
label-connected-margin=2px

label-disconnected=
label-disconnected-margin=2px

[module/wlan]
type=internal/network

interval=60
interface-type=wireless

format-connected=%{A3:xdg-run iwgtk:}%{A2:xdg-run gnome-nettool:}%{T2}<ramp-signal>%{T-}%{T5}<label-connected>%{T-}%{A}%{A}
format-connected-foreground=${colors.color10}
format-connected-margin=2px

label-connected=%local_ip%

label-disconnected=
label-disconnected-margin=2px

ramp-signal-0=󰤯
ramp-signal-1=󰤟
ramp-signal-2=󰤢
ramp-signal-3=󰤥
ramp-signal-4=󰤨

[module/pulseaudio]
type=internal/pulseaudio

format-volume=%{A3:xdg-run pavucontrol:}%{A2:xdg-run helvum:}%{T2}<ramp-volume>%{T-}%{T5}<label-volume>%{T-}%{A}%{A}
format-volume-foreground=${colors.color10}
format-volume-margin=2px

label-volume=%percentage%%

label-muted=%{A3:xdg-run pavucontrol:}%{A2:xdg-run helvum:}%{T2}󰸈%{T-}%{A}%{A}
label-muted-foreground=${colors.color9}
label-muted-margin=2px

ramp-volume-0=
ramp-volume-1=
ramp-volume-2=

[module/backlight]
type=internal/backlight

format=%{A4:brightnessctl -q s 5%+:}%{A5:brightnessctl -q s 5%-:}%{T2}<ramp>%{T-}%{A}%{A}
format-foreground=${colors.color13}
format-margin=2px

ramp-0=
ramp-1=
ramp-2=
ramp-3=
ramp-4=
ramp-5=
ramp-6=
ramp-7=
ramp-8=
ramp-9=
ramp-10=
ramp-11=
ramp-12=
ramp-13=

[module/date]
type=internal/date

interval=60

date=%{T2}󰥔%{T-}%{T5}%H:%M%{T-}
date-alt=%{T2}󰃭%{T-}%{T5}%Y-%m-%d%{T-}

label=%date%
label-foreground=${colors.color14}
label-margin=2px

[module/tray]
type=internal/tray

format-margin=2px
tray-size=100%
tray-spacing=2px


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
