# ${XDG_CONFIG_HOME}/sway/config.d/50-systemd-user.conf
# vim:ft=conf:fenc=utf-8:noet:ts=3:sw=3:

exec systemctl --user import-environment CLUTTER_BACKEND DESKTOP_SESSION GDK_BACKEND QT_QPA_PLATFORM SDL_VIDEODRIVER XDG_SESSION_TYPE WINIT_UNIX_BACKEND
exec dbus-update-activation-environment CLUTTER_BACKEND DESKTOP_SESSION GDK_BACKEND QT_QPA_PLATFORM SDL_VIDEODRIVER XDG_SESSION_TYPE WINIT_UNIX_BACKEND
