# ${XDG_CONFIG_HOME}/sway/config.d/inputs.conf
# vim:ft=conf:fenc=utf-8:noet:ts=3:sw=3:

input type:keyboard {
	repeat_delay 200
	repeat_rate  30
	xkb_options  compose:ralt
	xkb_numlock  enable
}

input type:touchpad {
	dwt           disabled
	events        disabled_on_external_mouse
	pointer_accel 0.5
	tap           enable
}
