# ${XDG_CONFIG_HOME}/sway/config.d/keybinds.conf
# vim:ft=conf:fenc=utf-8:noet:ts=3:sw=3:

bindsym {
	$meta+Return           exec launchyctl task terminald
	$meta+$alt+Return      exec launchyctl alt terminald
	$meta+Shift+Return     exec launchyctl end terminald
	$meta+Ctrl+Return      exec terminal
	$meta+Ctrl+$alt+Return exec termux

	Menu       exec launchyctl task launcherd
	Shift+Menu exec launchyctl end launcherd
	$alt+Menu  exec bemenu-run

	$meta+Shift+q kill
	$meta+Shift+c reload
	$meta+Shift+e exec swaynag -t warning -m 'Are you sure you want to exit Sway?' -b 'Exit' 'swaymsg exit' -s 'Cancel'

	$meta+$down  focus down
	$meta+$left  focus left
	$meta+$right focus right
	$meta+$up    focus up

	$meta+Down  focus down
	$meta+Left  focus left
	$meta+Right focus right
	$meta+Up    focus up

	$meta+Shift+$down  move down
	$meta+Shift+$left  move left
	$meta+Shift+$right move right
	$meta+Shift+$up    move up

	$meta+Shift+Down  move down
	$meta+Shift+Left  move left
	$meta+Shift+Right move right
	$meta+Shift+Up    move up

	$meta+1 workspace number 1
	$meta+2 workspace number 2
	$meta+3 workspace number 3
	$meta+4 workspace number 4
	$meta+5 workspace number 5
	$meta+6 workspace number 6
	$meta+7 workspace number 7
	$meta+8 workspace number 8
	$meta+9 workspace number 9

	$meta+comma  workspace prev
	$meta+period workspace next

	$meta+Shift+1 move container workspace number 1
	$meta+Shift+2 move container workspace number 2
	$meta+Shift+3 move container workspace number 3
	$meta+Shift+4 move container workspace number 4
	$meta+Shift+5 move container workspace number 5
	$meta+Shift+6 move container workspace number 6
	$meta+Shift+7 move container workspace number 7
	$meta+Shift+8 move container workspace number 8
	$meta+Shift+9 move container workspace number 9

	$meta+Shift+comma  move container workspace prev
	$meta+Shift+period move container workspace next

	$meta+r mode resize

	$meta+b splith
	$meta+v splitv

	$meta+s layout stacking
	$meta+w layout tabbed
	$meta+e layout toggle split

	$meta+f fullscreen

	$meta+Shift+space      floating toggle
	$meta+Ctrl+Shift+space sticky   toggle

	$meta+space focus mode_toggle
	$meta+a     focus parent

	$meta+Shift+minus move scratchpad
	$meta+minus       scratchpad show

	Print exec screenshot

	Insert       exec passmenu
	$alt+Insert  exec passmenu -q
	Shift+Insert exec passmenu -t

	XF86MonBrightnessUp   exec light -A 5
	XF86MonBrightnessDown exec light -U 5
}

bindsym --inhibited $meta+$alt+i seat * shortcuts_inhibitor toggle

bindsym --locked {
	XF86AudioLowerVolume exec pamixer --decrease 5
	XF86AudioMute        exec pamixer --toggle-mute
	XF86AudioRaiseVolume exec pamixer --increase 5

	XF86AudioNext  exec mpc next
	XF86AudioPlay  exec mpc play
	XF86AudioPause exec mpc pause
	XF86AudioPrev  exec mpc prev
	XF86AudioStop  exec mpc stop
}
