# ${XDG_CONFIG_HOME}/sway/config.d/modes.conf
# vim:ft=conf:fenc=utf-8:noet:ts=3:sw=3:

mode resize {
	bindsym {
		$left  resize shrink width 4px
		$down  resize grow height 4px
		$up    resize shrink height 4px
		$right resize grow width 4px

		Left  resize shrink width 4px
		Down  resize grow height 4px
		Up    resize shrink height 4px
		Right resize grow width 4px

		Shift+$left  resize shrink width 16px
		Shift+$down  resize grow height 16px
		Shift+$up    resize shrink height 16px
		Shift+$right resize grow width 16px

		Shift+Left  resize shrink width 16px
		Shift+Down  resize grow height 16px
		Shift+Up    resize shrink height 16px
		Shift+Right resize grow width 16px

		Return mode default
		Escape mode default
	}
}
