# ${XDG_CONFIG_HOME}/sway/config.d/swayidle.conf
# vim:ft=conf:fenc=utf-8:noet:ts=3:sw=3:

exec swayidle -w \
	before-sleep 'swaylock -f' \
	idlehint 300 \
	lock 'swaylock -f' \
	timeout 300 'swaymsg "output * dpms off"' \
		resume 'swaymsg "output * dpms on"' \
	timeout 300 'gdbus call --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1/session/auto --method org.freedesktop.login1.Session.SetLockedHint true' \
		resume 'gdbus call --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1/session/auto --method org.freedesktop.login1.Session.SetLockedHint false' \
	timeout 300 'swaylock -f'
