#!/bin/sh
# vim:ft=sh:noet:ts=3:sw=3:
# file:$XDG_CONFIG_HOME/openbox/autostart
#==============================================================================#


picom -b

unclutter -b --timeout 3 --ignore-buttons 4,5,6,7

xss-lock -s "$XDG_SESSION_ID" -l -- i3lock -n -u -c 000000 &

systemctl -q --user start openbox-session.target


#==============================================================================#
#                                 END OF FILE                                  #
#==============================================================================#
